Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: org.example.HandlerS3
      CodeUri: D:\dev\projekty\LambdaPdfToText
      Runtime: java11
      Architectures:
        - x86_64